### PR TITLE
Workaround qt bug on QRegularExpression;  Fix #2593

### LINKED ISSUE #2593: latest 5.2.0 fails to build with Qt 6.6.0
Hi,

I tried on Mageia Cauldron to build latest kvirc 5.2.0 but it fails to build with the following error:

`/home/iurt/rpmbuild/BUILD/KVIrc-5.2.0/src/kvilib/ext/KviRegExp.cpp: In member function 'QString KviRegExp::getCompletePattern() const':
/home/iurt/rpmbuild/BUILD/KVIrc-5.2.0/src/kvilib/ext/KviRegExp.cpp:37:134: error: invalid conversion from 'int' to 'QRegularExpression::WildcardConversionOption' [-fpermissive]
   37 |                 return QRegularExpression::wildcardToRegularExpression(m_szPattern, QRegularExpression::UnanchoredWildcardConversion | QRegularExpression::NonPathWildcardConversion);`

This is with Qt 6.6.0

Attached the full build log:
[build.x86_64.0.20240120155705.log](https://github.com/kvirc/KVIrc/files/13998456/build.x86_64.0.20240120155705.log)

### PR DESCRIPTION
**Pull request by ctrlaltca**
Qt 6.6.0 misses the | operator for QRegularExpression::WildcardConversionOptions
Require Qt 6.6.1 for the codepath using it
See also: https://codereview.qt-project.org/c/qt/qtbase/+/511939

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Could https://github.com/kvirc/KVIrc/blob/master/CMakeLists.txt#L388 check the Qt6 version? (either by number, or checking whether QRegularExpression has everything necessary)

**Comment by ctrlaltca** [comment]
Yes, we could require a specific min version for both Qt5 and Qt6.

**Review by DarthGandalf — APPROVED** [review]
