### ISSUE TITLE
Compilation failure: src/modules/dcc/DccVideoWindow.h:107:7: error: ‘bool DccVideoThread::handleIncomingData(KviDccThreadIncomingData*, bool)’ marked ‘override’, but does not override

### ISSUE THREAD

**Issue by Arfrever** [kvirc/KVIrc#2436]
```
FAILED: src/modules/dcc/CMakeFiles/kvidcc.dir/kvidcc_autogen/mocs_compilation.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -Dkvidcc_EXPORTS -Isrc/modules/dcc/kvidcc_autogen/include -I/usr/include/python2.7 -I/usr/include/enchant-2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I. -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/tal -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/config -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/core -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/ext -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/file -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/irc -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/locale -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/net -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvilib/system -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/kernel -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/kvs -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/kvs/event -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/kvs/object -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/kvs/parser -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/kvs/tree -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/module -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/sparser -I/var/tmp/portage/net-irc/kvirc-5.2_pre20190626025832/work/KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/../kvirc/ui -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtMultimediaWidgets -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5 -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5/KXmlGui -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KConfigWidgets -isystem /usr/include/KF5/KCodecs -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/KF5/KConfigGui -isystem /usr/include/KF5/KAuth -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5/KNotifications -isystem /usr/include/KF5/KService -isystem /usr/include/phonon4qt5  -DNDEBUG -march=native -O2 -pipe -Wall -Werror=terminate -fno-strict-aliasing -fPIC   -fPIC -std=gnu++17 -MD -MT src/modules/dcc/CMakeFiles/kvidcc.dir/kvidcc_autogen/mocs_compilation.cpp.o -MF src/modules/dcc/CMakeFiles/kvidcc.dir/kvidcc_autogen/mocs_compilation.cpp.o.d -o src/modules/dcc/CMakeFiles/kvidcc.dir/kvidcc_autogen/mocs_compilation.cpp.o -c src/modules/dcc/kvidcc_autogen/mocs_compilation.cpp
In file included from src/modules/dcc/kvidcc_autogen/EWIEGA46WW/moc_DccVideoWindow.cpp:9,
                 from src/modules/dcc/kvidcc_autogen/mocs_compilation.cpp:8:
src/modules/dcc/kvidcc_autogen/EWIEGA46WW/../../../../../../KVIrc-3f0172591f580b7209f8528bdb202dde0acfd51d/src/modules/dcc/DccVideoWindow.h:107:7: error: ‘bool DccVideoThread::handleIncomingData(KviDccThreadIncomingData*, bool)’ marked ‘override’, but does not override
  bool handleIncomingData(KviDccThreadIncomingData * data, bool bCritical) override;
       ^~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```
GCC 8.3.0 is used here.

This error seems to have been introduced in commit 2c52bee29d4636bcdce407ac91b353d34d89258c.

Fix working for me:
```
--- src/modules/dcc/DccVideoWindow.h
+++ src/modules/dcc/DccVideoWindow.h
@@ -104,7 +104,7 @@
        void stopPlaying();
        bool isPlaying() const { return m_bPlaying; }
        void run() override;
-       bool handleIncomingData(KviDccThreadIncomingData * data, bool bCritical) override;
+       bool handleIncomingData(KviDccThreadIncomingData * data, bool bCritical);
 };
 
 class DccVideoWindow : public DccWindow
```
After applying above change, the rest of KVIrc has been built successfully.

**Comment by IceN9ne** [comment]
Fixed in 2fe1a3b
