### ISSUE TITLE
Can't compile with crypto++ 5.5.2

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#645]
**Reported by wrar on 12 Dec 2009 16:38:56 UTC**
src/modules/rijndael/libkvirijndael_cryptopp.cpp:170: error: 'BlockPaddingSchemeDef' is not a member of 'CryptoPP'

Indeed:

```
$ fgrep BlockPaddingScheme /usr/include/cryptopp
/usr/include/cryptopp/filters.h:        enum BlockPaddingScheme {NO_PADDING, ZEROS_PADDING, PKCS_PADDING, ONE_AND_ZEROS_PADDING, DEFAULT_PADDING};
/usr/include/cryptopp/filters.h:        StreamTransformationFilter(StreamTransformation &c, BufferedTransformation *attachment = NULL, BlockPaddingScheme padding = DEFAULT_PADDING);
/usr/include/cryptopp/filters.h:        static size_t LastBlockSize(StreamTransformation &c, BlockPaddingScheme padding);
/usr/include/cryptopp/filters.h:        BlockPaddingScheme m_padding;
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/645

**Comment by DarthGandalf** [comment]
**Modified by anonymous on 12 Dec 2009 16:51:44**
Summary: Can't compile with crypto++ 5.6.0 → Can't compile with crypto++ 5.5.2

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 12 Dec 2009 16:53:29**
Either fix the code or update the version requirement in CMakeLists.txt.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 12 Dec 2009 17:20:31**
fixed in r3692

---

Resolution: none → fixed
Status: new → closed
