### ISSUE TITLE
latest 5.2.0 fails to build with Qt 6.6.0

### ISSUE THREAD

**Issue by david-geiger** [kvirc/KVIrc#2593]
Hi,

I tried on Mageia Cauldron to build latest kvirc 5.2.0 but it fails to build with the following error:

`/home/iurt/rpmbuild/BUILD/KVIrc-5.2.0/src/kvilib/ext/KviRegExp.cpp: In member function 'QString KviRegExp::getCompletePattern() const':
/home/iurt/rpmbuild/BUILD/KVIrc-5.2.0/src/kvilib/ext/KviRegExp.cpp:37:134: error: invalid conversion from 'int' to 'QRegularExpression::WildcardConversionOption' [-fpermissive]
   37 |                 return QRegularExpression::wildcardToRegularExpression(m_szPattern, QRegularExpression::UnanchoredWildcardConversion | QRegularExpression::NonPathWildcardConversion);`

This is with Qt 6.6.0

Attached the full build log:
[build.x86_64.0.20240120155705.log](https://github.com/kvirc/KVIrc/files/13998456/build.x86_64.0.20240120155705.log)

**Comment by ctrlaltca** [comment]
Yep, Qt 6.6.0 missed the | operator for QRegularExpression flags.
The fix is in https://codereview.qt-project.org/c/qt/qtbase/+/511939
I'm sorry you probably need Qt 6.6.1 to get this working.
Since we already have 3 different code paths for Qt5, Qt6 and Qt>=6.6, we could just require 6.6.1 to avoid this problem

**Comment by ctrlaltca** [comment]
Fix is in https://github.com/kvirc/KVIrc/pull/2594

**Comment by david-geiger** [comment]
Another build issue with Qt 6.6.0:

`/home/iurt/rpmbuild/BUILD/KVIrc-5.2.0/build/src/modules/dcc/kvidcc_autogen/EWIEGA46WW/../../../../../../src/modules/dcc/DccVideoWindow.h:48:10: fatal error: QCameraViewfinder: No such file or directory
   48 | #include <QCameraViewfinder>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/module`

`#include <QCameraViewfinder>` does not exist in Qt6.

**Comment by DarthGandalf** [comment]
> 3 different code paths for Qt5, Qt6 and Qt>=6.6

Why do we need the codepath for 6<=Qt<6.6?

**Comment by ctrlaltca** [comment]
> Why do we need the codepath for 6<=Qt<6.6?

In an attempt to avoid limiting Qt6 to >= 6.6.1, that is quite recent and probably unavailable on most distros.

**Comment by ctrlaltca** [comment]
> `#include <QCameraViewfinder>` does not exist in Qt6.

Yep, dcc video needs a rewrite to work on Qt6. Not that it really worked in Qt5, it was mostly a proof of concept; eg. all the video controls aren't even wired to actual functions.

**Comment by DarthGandalf** [comment]
I don't think Qt5 is being removed from any distro yet, so I'd be fine requiring new enough Qt6. But ok, up to you.
